### ISSUE TITLE
dendrite or matrix-bot-sdk error when creating rooms

### ISSUE THREAD

**Issue by jjj333-p** [jjj333-p/dendrite-admin-interface#8]
putting information here to sort out my brain

something about https://github.com/jjj333-p/dendrite-admin-interface/blob/d854644f673f0258f1072ff29ec58b219d3e81eb/index.js#L34 

on the client/bot side it just returns that there was an internal server error

on dendrite side this shows up in the logs (this snippet unescaped for your reading pleasure :woozy_face: )

```
Dec 14 04:40:42 snapshot-115842185-debian-2gb-hil-1 dendrite[749421]: time="2023-12-14T04:40:42.371416083Z" level=info msg="Creating new room" req.id=vmQEUHFqLH2r req.method=POST req.path=/_matrix/client/v3/createRoom roomID="!pHXDcUbz4engft23:pain.agency" roomVersion=10 userID="@admin:pain.agency" user_id="@admin:pain.agency"
Dec 14 04:40:42 snapshot-115842185-debian-2gb-hil-1 dendrite[749421]: time="2023-12-14T04:40:42.377718640Z" level=error msg="Request panicked!
goroutine 33085 [running]:
runtime/debug.Stack()
   /usr/lib/golang/src/runtime/debug/stack.go:24 +0x65
github.com/matrix-org/util.Protect.func1.1()
   /home/joseph/go/pkg/mod/github.com/matrix-org/util@v0.0.0-20221111132719-399730281e66/json.go:98 +0x157
panic({0x16306e0, 0x247b0e0})
   /usr/lib/golang/src/runtime/panic.go:884 +0x213
github.com/matrix-org/dendrite/internal/httputil.MakeAuthAPI.func1.1()
   /home/joseph/dendrite/dendrite/internal/httputil/httpapi.go:91 +0x52
panic({0x16306e0, 0x247b0e0})
   /usr/lib/golang/src/runtime/panic.go:884 +0x213
github.com/matrix-org/gomatrixserverlib/spec.(*UserID).String(...)
   /home/joseph/go/pkg/mod/github.com/matrix-org/gomatrixserverlib@v0.0.0-20231212115925-41497b7563eb/spec/userid.go:37
github.com/matrix-org/gomatrixserverlib.(*allowerContext).powerLevelsEventAllowed(0xc01b816420, {0x1ad8e38, 0xc017052280})
   /home/joseph/go/pkg/mod/github.com/matrix-org/gomatrixserverlib@v0.0.0-20231212115925-41497b7563eb/eventauth.go:529 +0x34c
github.com/matrix-org/gomatrixserverlib.(*allowerContext).allowed(0xc01b816420?, {0x1ad8e38, 0xc017052280})
   /home/joseph/go/pkg/mod/github.com/matrix-org/gomatrixserverlib@v0.0.0-20231212115925-41497b7563eb/eventauth.go:404 +0x1b1
github.com/matrix-org/gomatrixserverlib.Allowed({0x1ad8e38, 0xc017052280}, {0x1ac8ad8, 0xc010432460}, 0xc00ab62e20)
   /home/joseph/go/pkg/mod/github.com/matrix-org/gomatrixserverlib@v0.0.0-20231212115925-41497b7563eb/eventauth.go:419 +0x17f
github.com/matrix-org/dendrite/roomserver/internal/perform.(*Creator).PerformCreateRoom(0xc009e5a420, {0x1ac3d88?, 0xc016d36540}, {{0xc00c214690, 0x12}, {0xc00c214691, 0x5}, {0xc00c214697, 0xb}}, {{0xc01656bc80, ...}, ...}, ...)
   /home/joseph/dendrite/dendrite/roomserver/internal/perform/perform_create_room.go:400 +0x3872
github.com/matrix-org/dendrite/roomserver/internal.(*RoomserverInternalAPI).PerformCreateRoom(0xc00a7f18c0?, {0x1ac3d88?, 0xc016d36540?}, {{0xc00c214690, 0x12}, {0xc00c214691, 0x5}, {0xc00c214697, 0xb}}, {{0xc01656bc80, ...}, ...}, ...)
   /home/joseph/dendrite/dendrite/roomserver/internal/api.go:248 +0xb2
github.com/matrix-org/dendrite/clientapi/routing.createRoom({_, _}, {{0xc00a761640, 0x1, 0x4}, {0xc00cfbcd98, 0x13}, {0x0, 0x0}, {0x0, ...}, ...}, ...)
   /home/joseph/dendrite/dendrite/clientapi/routing/createroom.go:228 +0xeb7
github.com/matrix-org/dendrite/clientapi/routing.CreateRoom(0xc01224cb00, 0xc000063000?, 0xc007627260?, {0x7fdac2437260, 0xc00a7f18c0}, {0x7fdac2437108, 0xc006927080}, {0x1ac6080, 0xc00b53dfb0})
   /home/joseph/dendrite/dendrite/clientapi/routing/createroom.go:132 +0x1e6
github.com/matrix-org/dendrite/clientapi/routing.Setup.func16(0x1ac3d88?, 0x15add00?)
   /home/joseph/dendrite/dendrite/clientapi/routing/routing.go:312 +0x35
github.com/matrix-org/dendrite/internal/httputil.MakeAuthAPI.func1(0xc01224c600)
   /home/joseph/dendrite/dendrite/internal/httputil/httpapi.go:108 +0x5e8
github.com/matrix-org/util.(*jsonRequestHandlerWrapper).OnIncomingRequest(0xc01224c000?, 0x42b925?)
   /home/joseph/go/pkg/mod/github.com/matrix-org/util@v0.0.0-20221111132719-399730281e66/json.go:79 +0x1f
github.com/matrix-org/util.MakeJSONAPI.func1({0x1ac29c0, 0xc01a651b20}, 0xc01224c000?)
   /home/joseph/go/pkg/mod/github.com/matrix-org/util@v0.0.0-20221111132719-399730281e66/json.go:141 +0xcd
github.com/matrix-org/util.Protect.func1({0x1ac29c0?, 0xc01a651b20?}, 0x1833e09?)
   /home/joseph/go/pkg/mod/github.com/matrix-org/util@v0.0.0-20221111132719-399730281e66/json.go:103 +0x72
net/http.HandlerFunc.ServeHTTP(...)
   /usr/lib/golang/src/net/http/server.go:2122
github.com/matrix-org/dendrite/internal/httputil.MakeExternalAPI.func1({0x1ac29c0?, 0xc01a651b20?}, 0xc011cd5f00)
   /home/joseph/dendrite/dendrite/internal/httputil/httpapi.go:191 +0x413
net/http.HandlerFunc.ServeHTTP(0xc011cd5e00?, {0x1ac29c0?, 0xc01a651b20?}, 0x174ccc0?)
   /usr/lib/golang/src/net/http/server.go:2122 +0x2f
github.com/gorilla/mux.(*Router).ServeHTTP(0xc000174600, {0x1ac29c0, 0xc01a651b20}, 0xc011cd5d00)
   /home/joseph/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1cf
github.com/gorilla/mux.(*Router).ServeHTTP(0xc00c18d080, {0x1ac29c0, 0xc01a651b20}, 0xc011cd5800)
   /home/joseph/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1cf
net/http.serverHandler.ServeHTTP({0x1abfb98?}, {0x1ac29c0, 0xc01a651b20}, 0xc011cd5800)
   /usr/lib/golang/src/net/http/server.go:2936 +0x316
net/http.(*conn).serve(0xc0093b4510, {0x1ac3d88, 0xc00ba57260})
   /usr/lib/golang/src/net/http/server.go:1995 +0x612
created by net/http.(*Server).Serve
   /usr/lib/golang/src/net/http/server.go:3089 +0x5ed
" context=missing panic="runtime error: invalid memory address or nil pointer dereference"
```

this only seems to happen when using the bot sdk? i need to figure out what exactly is creating this issue, then probably forward that information on to the dendrite team as its a pretty serious bug

**Comment by jjj333-p** [comment]
fixed with https://github.com/jjj333-p/dendrite-admin-interface/commit/454cd29bb11bd90ad7ac59d35e996962a445a5fb
